### Generated by Winemaker 0.8.1
###
### Invocation command line was
### /usr/bin/winemaker --lower-uppercase . --wine32 -iddraw


SRCDIR                = .
SUBDIRS               =
DLLS                  =
LIBS                  =
EXES                  = demo8_1.exe \
			demo8_10.exe \
			demo8_10_16b.exe \
			demo8_11.exe \
			demo8_11_16b.exe \
			demo8_12.exe \
			demo8_12_16b.exe \
			demo8_2.exe \
			demo8_3.exe \
			demo8_4.exe \
			demo8_5.exe \
			demo8_6.exe \
			demo8_7.exe \
			demo8_8.exe \
			demo8_9.exe \
			t3dconsole.exe \



### Common settings

CEXTRA                = -mno-cygwin \
			-m32
CXXEXTRA              = -mno-cygwin \
			-m32 \
			-masm=intel
RCEXTRA               =
DEFINES               =
INCLUDE_PATH          = -I.
DLL_PATH              =
DLL_IMPORTS           = ddraw
LIBRARY_PATH          =
LIBRARIES             =


### Extra source lists

EXTRA_C_SRCS          =
EXTRA_CXX_SRCS        = t3dlib1.cpp
EXTRA_RC_SRCS         =

EXTRA_OBJS            = $(EXTRA_C_SRCS:.c=.o) \
			$(EXTRA_CXX_SRCS:.cpp=.o)



### demo8_1.exe sources and settings

demo8_1_exe_MODULE    = demo8_1.exe
demo8_1_exe_C_SRCS    =
demo8_1_exe_CXX_SRCS  = demo8_1.cpp
demo8_1_exe_RC_SRCS   =
demo8_1_exe_LDFLAGS   = -mwindows \
			-mno-cygwin \
			-m32
demo8_1_exe_ARFLAGS   =
demo8_1_exe_DLL_PATH  =
demo8_1_exe_DLLS      = odbc32 \
			ole32 \
			oleaut32 \
			winspool \
			odbccp32
demo8_1_exe_LIBRARY_PATH=
demo8_1_exe_LIBRARIES = uuid

demo8_1_exe_OBJS      = $(demo8_1_exe_C_SRCS:.c=.o) \
			$(demo8_1_exe_CXX_SRCS:.cpp=.o) \
			$(demo8_1_exe_RC_SRCS:.rc=.res)



### demo8_10.exe sources and settings

demo8_10_exe_MODULE   = demo8_10.exe
demo8_10_exe_C_SRCS   =
demo8_10_exe_CXX_SRCS = demo8_10.cpp
demo8_10_exe_RC_SRCS  =
demo8_10_exe_LDFLAGS  = -mwindows \
			-mno-cygwin \
			-m32
demo8_10_exe_ARFLAGS  =
demo8_10_exe_DLL_PATH =
demo8_10_exe_DLLS     = odbc32 \
			ole32 \
			oleaut32 \
			winspool \
			odbccp32
demo8_10_exe_LIBRARY_PATH=
demo8_10_exe_LIBRARIES= uuid

demo8_10_exe_OBJS     = $(demo8_10_exe_C_SRCS:.c=.o) \
			$(demo8_10_exe_CXX_SRCS:.cpp=.o) \
			$(EXTRA_OBJS) \
			$(demo8_10_exe_RC_SRCS:.rc=.res)



### demo8_10_16b.exe sources and settings

demo8_10_16b_exe_MODULE= demo8_10_16b.exe
demo8_10_16b_exe_C_SRCS=
demo8_10_16b_exe_CXX_SRCS= demo8_10_16b.cpp
demo8_10_16b_exe_RC_SRCS=
demo8_10_16b_exe_LDFLAGS= -mwindows \
			-mno-cygwin \
			-m32
demo8_10_16b_exe_ARFLAGS=
demo8_10_16b_exe_DLL_PATH=
demo8_10_16b_exe_DLLS = odbc32 \
			ole32 \
			oleaut32 \
			winspool \
			odbccp32
demo8_10_16b_exe_LIBRARY_PATH=
demo8_10_16b_exe_LIBRARIES= uuid

demo8_10_16b_exe_OBJS = $(demo8_10_16b_exe_C_SRCS:.c=.o) \
			$(demo8_10_16b_exe_CXX_SRCS:.cpp=.o) \
			$(EXTRA_OBJS) \
			$(demo8_10_16b_exe_RC_SRCS:.rc=.res)



### demo8_11.exe sources and settings

demo8_11_exe_MODULE   = demo8_11.exe
demo8_11_exe_C_SRCS   =
demo8_11_exe_CXX_SRCS = demo8_11.cpp
demo8_11_exe_RC_SRCS  =
demo8_11_exe_LDFLAGS  = -mwindows \
			-mno-cygwin \
			-m32
demo8_11_exe_ARFLAGS  =
demo8_11_exe_DLL_PATH =
demo8_11_exe_DLLS     = odbc32 \
			ole32 \
			oleaut32 \
			winspool \
			odbccp32
demo8_11_exe_LIBRARY_PATH=
demo8_11_exe_LIBRARIES= uuid

demo8_11_exe_OBJS     = $(demo8_11_exe_C_SRCS:.c=.o) \
			$(demo8_11_exe_CXX_SRCS:.cpp=.o) \
			$(EXTRA_OBJS) \
			$(demo8_11_exe_RC_SRCS:.rc=.res)



### demo8_11_16b.exe sources and settings

demo8_11_16b_exe_MODULE= demo8_11_16b.exe
demo8_11_16b_exe_C_SRCS=
demo8_11_16b_exe_CXX_SRCS= demo8_11_16b.cpp
demo8_11_16b_exe_RC_SRCS=
demo8_11_16b_exe_LDFLAGS= -mwindows \
			-mno-cygwin \
			-m32
demo8_11_16b_exe_ARFLAGS=
demo8_11_16b_exe_DLL_PATH=
demo8_11_16b_exe_DLLS = odbc32 \
			ole32 \
			oleaut32 \
			winspool \
			odbccp32
demo8_11_16b_exe_LIBRARY_PATH=
demo8_11_16b_exe_LIBRARIES= uuid

demo8_11_16b_exe_OBJS = $(demo8_11_16b_exe_C_SRCS:.c=.o) \
			$(demo8_11_16b_exe_CXX_SRCS:.cpp=.o) \
			$(EXTRA_OBJS) \
			$(demo8_11_16b_exe_RC_SRCS:.rc=.res)



### demo8_12.exe sources and settings

demo8_12_exe_MODULE   = demo8_12.exe
demo8_12_exe_C_SRCS   =
demo8_12_exe_CXX_SRCS = demo8_12.cpp
demo8_12_exe_RC_SRCS  =
demo8_12_exe_LDFLAGS  = -mwindows \
			-mno-cygwin \
			-m32
demo8_12_exe_ARFLAGS  =
demo8_12_exe_DLL_PATH =
demo8_12_exe_DLLS     = odbc32 \
			ole32 \
			oleaut32 \
			winspool \
			odbccp32
demo8_12_exe_LIBRARY_PATH=
demo8_12_exe_LIBRARIES= uuid

demo8_12_exe_OBJS     = $(demo8_12_exe_C_SRCS:.c=.o) \
			$(demo8_12_exe_CXX_SRCS:.cpp=.o) \
			$(EXTRA_OBJS) \
			$(demo8_12_exe_RC_SRCS:.rc=.res)



### demo8_12_16b.exe sources and settings

demo8_12_16b_exe_MODULE= demo8_12_16b.exe
demo8_12_16b_exe_C_SRCS=
demo8_12_16b_exe_CXX_SRCS= demo8_12_16b.cpp
demo8_12_16b_exe_RC_SRCS=
demo8_12_16b_exe_LDFLAGS= -mwindows \
			-mno-cygwin \
			-m32
demo8_12_16b_exe_ARFLAGS=
demo8_12_16b_exe_DLL_PATH=
demo8_12_16b_exe_DLLS = odbc32 \
			ole32 \
			oleaut32 \
			winspool \
			odbccp32
demo8_12_16b_exe_LIBRARY_PATH=
demo8_12_16b_exe_LIBRARIES= uuid

demo8_12_16b_exe_OBJS = $(demo8_12_16b_exe_C_SRCS:.c=.o) \
			$(demo8_12_16b_exe_CXX_SRCS:.cpp=.o) \
			$(EXTRA_OBJS) \
			$(demo8_12_16b_exe_RC_SRCS:.rc=.res)



### demo8_2.exe sources and settings

demo8_2_exe_MODULE    = demo8_2.exe
demo8_2_exe_C_SRCS    =
demo8_2_exe_CXX_SRCS  = demo8_2.cpp
demo8_2_exe_RC_SRCS   =
demo8_2_exe_LDFLAGS   = -mwindows \
			-mno-cygwin \
			-m32
demo8_2_exe_ARFLAGS   =
demo8_2_exe_DLL_PATH  =
demo8_2_exe_DLLS      = odbc32 \
			ole32 \
			oleaut32 \
			winspool \
			odbccp32
demo8_2_exe_LIBRARY_PATH=
demo8_2_exe_LIBRARIES = uuid

demo8_2_exe_OBJS      = $(demo8_2_exe_C_SRCS:.c=.o) \
			$(demo8_2_exe_CXX_SRCS:.cpp=.o) \
			$(demo8_2_exe_RC_SRCS:.rc=.res)



### demo8_3.exe sources and settings

demo8_3_exe_MODULE    = demo8_3.exe
demo8_3_exe_C_SRCS    =
demo8_3_exe_CXX_SRCS  = demo8_3.cpp
demo8_3_exe_RC_SRCS   =
demo8_3_exe_LDFLAGS   = -mwindows \
			-mno-cygwin \
			-m32
demo8_3_exe_ARFLAGS   =
demo8_3_exe_DLL_PATH  =
demo8_3_exe_DLLS      = odbc32 \
			ole32 \
			oleaut32 \
			winspool \
			odbccp32
demo8_3_exe_LIBRARY_PATH=
demo8_3_exe_LIBRARIES = uuid

demo8_3_exe_OBJS      = $(demo8_3_exe_C_SRCS:.c=.o) \
			$(demo8_3_exe_CXX_SRCS:.cpp=.o) \
			$(demo8_3_exe_RC_SRCS:.rc=.res)



### demo8_4.exe sources and settings

demo8_4_exe_MODULE    = demo8_4.exe
demo8_4_exe_C_SRCS    =
demo8_4_exe_CXX_SRCS  = demo8_4.cpp
demo8_4_exe_RC_SRCS   =
demo8_4_exe_LDFLAGS   = -mwindows \
			-mno-cygwin \
			-m32
demo8_4_exe_ARFLAGS   =
demo8_4_exe_DLL_PATH  =
demo8_4_exe_DLLS      = odbc32 \
			ole32 \
			oleaut32 \
			winspool \
			odbccp32
demo8_4_exe_LIBRARY_PATH=
demo8_4_exe_LIBRARIES = uuid

demo8_4_exe_OBJS      = $(demo8_4_exe_C_SRCS:.c=.o) \
			$(demo8_4_exe_CXX_SRCS:.cpp=.o) \
			$(demo8_4_exe_RC_SRCS:.rc=.res)



### demo8_5.exe sources and settings

demo8_5_exe_MODULE    = demo8_5.exe
demo8_5_exe_C_SRCS    =
demo8_5_exe_CXX_SRCS  = demo8_5.cpp
demo8_5_exe_RC_SRCS   =
demo8_5_exe_LDFLAGS   = -mwindows \
			-mno-cygwin \
			-m32
demo8_5_exe_ARFLAGS   =
demo8_5_exe_DLL_PATH  =
demo8_5_exe_DLLS      = odbc32 \
			ole32 \
			oleaut32 \
			winspool \
			odbccp32
demo8_5_exe_LIBRARY_PATH=
demo8_5_exe_LIBRARIES = uuid

demo8_5_exe_OBJS      = $(demo8_5_exe_C_SRCS:.c=.o) \
			$(demo8_5_exe_CXX_SRCS:.cpp=.o) \
			$(demo8_5_exe_RC_SRCS:.rc=.res)



### demo8_6.exe sources and settings

demo8_6_exe_MODULE    = demo8_6.exe
demo8_6_exe_C_SRCS    =
demo8_6_exe_CXX_SRCS  = demo8_6.cpp
demo8_6_exe_RC_SRCS   =
demo8_6_exe_LDFLAGS   = -mwindows \
			-mno-cygwin \
			-m32
demo8_6_exe_ARFLAGS   =
demo8_6_exe_DLL_PATH  =
demo8_6_exe_DLLS      = odbc32 \
			ole32 \
			oleaut32 \
			winspool \
			odbccp32
demo8_6_exe_LIBRARY_PATH=
demo8_6_exe_LIBRARIES = uuid

demo8_6_exe_OBJS      = $(demo8_6_exe_C_SRCS:.c=.o) \
			$(demo8_6_exe_CXX_SRCS:.cpp=.o) \
			$(demo8_6_exe_RC_SRCS:.rc=.res)



### demo8_7.exe sources and settings

demo8_7_exe_MODULE    = demo8_7.exe
demo8_7_exe_C_SRCS    =
demo8_7_exe_CXX_SRCS  = demo8_7.cpp
demo8_7_exe_RC_SRCS   =
demo8_7_exe_LDFLAGS   = -mwindows \
			-mno-cygwin \
			-m32
demo8_7_exe_ARFLAGS   =
demo8_7_exe_DLL_PATH  =
demo8_7_exe_DLLS      = odbc32 \
			ole32 \
			oleaut32 \
			winspool \
			odbccp32
demo8_7_exe_LIBRARY_PATH=
demo8_7_exe_LIBRARIES = uuid

demo8_7_exe_OBJS      = $(demo8_7_exe_C_SRCS:.c=.o) \
			$(demo8_7_exe_CXX_SRCS:.cpp=.o) \
			$(demo8_7_exe_RC_SRCS:.rc=.res)



### demo8_8.exe sources and settings

demo8_8_exe_MODULE    = demo8_8.exe
demo8_8_exe_C_SRCS    =
demo8_8_exe_CXX_SRCS  = demo8_8.cpp
demo8_8_exe_RC_SRCS   =
demo8_8_exe_LDFLAGS   = -mwindows \
			-mno-cygwin \
			-m32
demo8_8_exe_ARFLAGS   =
demo8_8_exe_DLL_PATH  =
demo8_8_exe_DLLS      = odbc32 \
			ole32 \
			oleaut32 \
			winspool \
			odbccp32
demo8_8_exe_LIBRARY_PATH=
demo8_8_exe_LIBRARIES = uuid

demo8_8_exe_OBJS      = $(demo8_8_exe_C_SRCS:.c=.o) \
			$(demo8_8_exe_CXX_SRCS:.cpp=.o) \
			$(demo8_8_exe_RC_SRCS:.rc=.res)



### demo8_9.exe sources and settings

demo8_9_exe_MODULE    = demo8_9.exe
demo8_9_exe_C_SRCS    =
demo8_9_exe_CXX_SRCS  = demo8_9.cpp
demo8_9_exe_RC_SRCS   =
demo8_9_exe_LDFLAGS   = -mwindows \
			-mno-cygwin \
			-m32
demo8_9_exe_ARFLAGS   =
demo8_9_exe_DLL_PATH  =
demo8_9_exe_DLLS      = odbc32 \
			ole32 \
			oleaut32 \
			winspool \
			odbccp32
demo8_9_exe_LIBRARY_PATH=
demo8_9_exe_LIBRARIES = uuid

demo8_9_exe_OBJS      = $(demo8_9_exe_C_SRCS:.c=.o) \
			$(demo8_9_exe_CXX_SRCS:.cpp=.o) \
			$(demo8_9_exe_RC_SRCS:.rc=.res)



### t3dconsole.exe sources and settings

t3dconsole_exe_MODULE = t3dconsole.exe
t3dconsole_exe_C_SRCS =
t3dconsole_exe_CXX_SRCS= t3dconsole.cpp
t3dconsole_exe_RC_SRCS=
t3dconsole_exe_LDFLAGS= -mwindows \
			-mno-cygwin \
			-m32
t3dconsole_exe_ARFLAGS=
t3dconsole_exe_DLL_PATH=
t3dconsole_exe_DLLS   = odbc32 \
			ole32 \
			oleaut32 \
			winspool \
			odbccp32
t3dconsole_exe_LIBRARY_PATH=
t3dconsole_exe_LIBRARIES= uuid

t3dconsole_exe_OBJS   = $(t3dconsole_exe_C_SRCS:.c=.o) \
			$(t3dconsole_exe_CXX_SRCS:.cpp=.o) \
			$(t3dconsole_exe_RC_SRCS:.rc=.res)



### Global source lists

C_SRCS                = $(demo8_1_exe_C_SRCS) \
			$(demo8_10_exe_C_SRCS) \
			$(demo8_10_16b_exe_C_SRCS) \
			$(demo8_11_exe_C_SRCS) \
			$(demo8_11_16b_exe_C_SRCS) \
			$(demo8_12_exe_C_SRCS) \
			$(demo8_12_16b_exe_C_SRCS) \
			$(demo8_2_exe_C_SRCS) \
			$(demo8_3_exe_C_SRCS) \
			$(demo8_4_exe_C_SRCS) \
			$(demo8_5_exe_C_SRCS) \
			$(demo8_6_exe_C_SRCS) \
			$(demo8_7_exe_C_SRCS) \
			$(demo8_8_exe_C_SRCS) \
			$(demo8_9_exe_C_SRCS) \
			$(t3dconsole_exe_C_SRCS) \
			$(EXTRA_C_SRCS)
CXX_SRCS              = $(demo8_1_exe_CXX_SRCS) \
			$(demo8_10_exe_CXX_SRCS) \
			$(demo8_10_16b_exe_CXX_SRCS) \
			$(demo8_11_exe_CXX_SRCS) \
			$(demo8_11_16b_exe_CXX_SRCS) \
			$(demo8_12_exe_CXX_SRCS) \
			$(demo8_12_16b_exe_CXX_SRCS) \
			$(demo8_2_exe_CXX_SRCS) \
			$(demo8_3_exe_CXX_SRCS) \
			$(demo8_4_exe_CXX_SRCS) \
			$(demo8_5_exe_CXX_SRCS) \
			$(demo8_6_exe_CXX_SRCS) \
			$(demo8_7_exe_CXX_SRCS) \
			$(demo8_8_exe_CXX_SRCS) \
			$(demo8_9_exe_CXX_SRCS) \
			$(t3dconsole_exe_CXX_SRCS) \
			$(EXTRA_CXX_SRCS)
RC_SRCS               = $(demo8_1_exe_RC_SRCS) \
			$(demo8_10_exe_RC_SRCS) \
			$(demo8_10_16b_exe_RC_SRCS) \
			$(demo8_11_exe_RC_SRCS) \
			$(demo8_11_16b_exe_RC_SRCS) \
			$(demo8_12_exe_RC_SRCS) \
			$(demo8_12_16b_exe_RC_SRCS) \
			$(demo8_2_exe_RC_SRCS) \
			$(demo8_3_exe_RC_SRCS) \
			$(demo8_4_exe_RC_SRCS) \
			$(demo8_5_exe_RC_SRCS) \
			$(demo8_6_exe_RC_SRCS) \
			$(demo8_7_exe_RC_SRCS) \
			$(demo8_8_exe_RC_SRCS) \
			$(demo8_9_exe_RC_SRCS) \
			$(t3dconsole_exe_RC_SRCS) \
			$(EXTRA_RC_SRCS)


### Tools

CC = winegcc
CXX = wineg++
RC = wrc
AR = ar


### Generic targets

all: $(SUBDIRS) $(DLLS:%=%.so) $(LIBS) $(EXES)

### Build rules

.PHONY: all clean dummy

$(SUBDIRS): dummy
	@cd $@ && $(MAKE)

# Implicit rules

.SUFFIXES: .cpp .rc .res
DEFINCL = $(INCLUDE_PATH) $(DEFINES) $(OPTIONS)

.c.o:
	$(CC) -c $(CFLAGS) $(CEXTRA) $(DEFINCL) -o $@ $<

.cpp.o:
	$(CXX) -c $(CXXFLAGS) $(CXXEXTRA) $(DEFINCL) -o $@ $<

.cxx.o:
	$(CXX) -c $(CXXFLAGS) $(CXXEXTRA) $(DEFINCL) -o $@ $<

.rc.res:
	$(RC) $(RCFLAGS) $(RCEXTRA) $(DEFINCL) -fo$@ $<

# Rules for cleaning

CLEAN_FILES     = y.tab.c y.tab.h lex.yy.c core *.orig *.rej \
                  \\\#*\\\# *~ *% .\\\#*

clean:: $(SUBDIRS:%=%/__clean__) $(EXTRASUBDIRS:%=%/__clean__)
	$(RM) $(CLEAN_FILES) $(RC_SRCS:.rc=.res) $(C_SRCS:.c=.o) $(CXX_SRCS:.cpp=.o)
	$(RM) $(DLLS:%=%.so) $(LIBS) $(EXES) $(EXES:%=%.so)

$(SUBDIRS:%=%/__clean__): dummy
	cd `dirname $@` && $(MAKE) clean

$(EXTRASUBDIRS:%=%/__clean__): dummy
	-cd `dirname $@` && $(RM) $(CLEAN_FILES)

### Target specific build rules
DEFLIB = $(LIBRARY_PATH) $(LIBRARIES) $(DLL_PATH) $(DLL_IMPORTS:%=-l%)

$(demo8_1_exe_MODULE): $(demo8_1_exe_OBJS)
	$(CXX) $(demo8_1_exe_LDFLAGS) -o $@ $(demo8_1_exe_OBJS) $(demo8_1_exe_LIBRARY_PATH) $(DEFLIB) $(demo8_1_exe_DLLS:%=-l%) $(demo8_1_exe_LIBRARIES:%=-l%)


$(demo8_10_exe_MODULE): $(demo8_10_exe_OBJS)
	$(CXX) $(demo8_10_exe_LDFLAGS) -o $@ $(demo8_10_exe_OBJS) $(demo8_10_exe_LIBRARY_PATH) $(DEFLIB) $(demo8_10_exe_DLLS:%=-l%) $(demo8_10_exe_LIBRARIES:%=-l%)


$(demo8_10_16b_exe_MODULE): $(demo8_10_16b_exe_OBJS)
	$(CXX) $(demo8_10_16b_exe_LDFLAGS) -o $@ $(demo8_10_16b_exe_OBJS) $(demo8_10_16b_exe_LIBRARY_PATH) $(DEFLIB) $(demo8_10_16b_exe_DLLS:%=-l%) $(demo8_10_16b_exe_LIBRARIES:%=-l%)


$(demo8_11_exe_MODULE): $(demo8_11_exe_OBJS)
	$(CXX) $(demo8_11_exe_LDFLAGS) -o $@ $(demo8_11_exe_OBJS) $(demo8_11_exe_LIBRARY_PATH) $(DEFLIB) $(demo8_11_exe_DLLS:%=-l%) $(demo8_11_exe_LIBRARIES:%=-l%)


$(demo8_11_16b_exe_MODULE): $(demo8_11_16b_exe_OBJS)
	$(CXX) $(demo8_11_16b_exe_LDFLAGS) -o $@ $(demo8_11_16b_exe_OBJS) $(demo8_11_16b_exe_LIBRARY_PATH) $(DEFLIB) $(demo8_11_16b_exe_DLLS:%=-l%) $(demo8_11_16b_exe_LIBRARIES:%=-l%)


$(demo8_12_exe_MODULE): $(demo8_12_exe_OBJS)
	$(CXX) $(demo8_12_exe_LDFLAGS) -o $@ $(demo8_12_exe_OBJS) $(demo8_12_exe_LIBRARY_PATH) $(DEFLIB) $(demo8_12_exe_DLLS:%=-l%) $(demo8_12_exe_LIBRARIES:%=-l%)


$(demo8_12_16b_exe_MODULE): $(demo8_12_16b_exe_OBJS)
	$(CXX) $(demo8_12_16b_exe_LDFLAGS) -o $@ $(demo8_12_16b_exe_OBJS) $(demo8_12_16b_exe_LIBRARY_PATH) $(DEFLIB) $(demo8_12_16b_exe_DLLS:%=-l%) $(demo8_12_16b_exe_LIBRARIES:%=-l%)


$(demo8_2_exe_MODULE): $(demo8_2_exe_OBJS)
	$(CXX) $(demo8_2_exe_LDFLAGS) -o $@ $(demo8_2_exe_OBJS) $(demo8_2_exe_LIBRARY_PATH) $(DEFLIB) $(demo8_2_exe_DLLS:%=-l%) $(demo8_2_exe_LIBRARIES:%=-l%)


$(demo8_3_exe_MODULE): $(demo8_3_exe_OBJS)
	$(CXX) $(demo8_3_exe_LDFLAGS) -o $@ $(demo8_3_exe_OBJS) $(demo8_3_exe_LIBRARY_PATH) $(DEFLIB) $(demo8_3_exe_DLLS:%=-l%) $(demo8_3_exe_LIBRARIES:%=-l%)


$(demo8_4_exe_MODULE): $(demo8_4_exe_OBJS)
	$(CXX) $(demo8_4_exe_LDFLAGS) -o $@ $(demo8_4_exe_OBJS) $(demo8_4_exe_LIBRARY_PATH) $(DEFLIB) $(demo8_4_exe_DLLS:%=-l%) $(demo8_4_exe_LIBRARIES:%=-l%)


$(demo8_5_exe_MODULE): $(demo8_5_exe_OBJS)
	$(CXX) $(demo8_5_exe_LDFLAGS) -o $@ $(demo8_5_exe_OBJS) $(demo8_5_exe_LIBRARY_PATH) $(DEFLIB) $(demo8_5_exe_DLLS:%=-l%) $(demo8_5_exe_LIBRARIES:%=-l%)


$(demo8_6_exe_MODULE): $(demo8_6_exe_OBJS)
	$(CXX) $(demo8_6_exe_LDFLAGS) -o $@ $(demo8_6_exe_OBJS) $(demo8_6_exe_LIBRARY_PATH) $(DEFLIB) $(demo8_6_exe_DLLS:%=-l%) $(demo8_6_exe_LIBRARIES:%=-l%)


$(demo8_7_exe_MODULE): $(demo8_7_exe_OBJS)
	$(CXX) $(demo8_7_exe_LDFLAGS) -o $@ $(demo8_7_exe_OBJS) $(demo8_7_exe_LIBRARY_PATH) $(DEFLIB) $(demo8_7_exe_DLLS:%=-l%) $(demo8_7_exe_LIBRARIES:%=-l%)


$(demo8_8_exe_MODULE): $(demo8_8_exe_OBJS)
	$(CXX) $(demo8_8_exe_LDFLAGS) -o $@ $(demo8_8_exe_OBJS) $(demo8_8_exe_LIBRARY_PATH) $(DEFLIB) $(demo8_8_exe_DLLS:%=-l%) $(demo8_8_exe_LIBRARIES:%=-l%)


$(demo8_9_exe_MODULE): $(demo8_9_exe_OBJS)
	$(CXX) $(demo8_9_exe_LDFLAGS) -o $@ $(demo8_9_exe_OBJS) $(demo8_9_exe_LIBRARY_PATH) $(DEFLIB) $(demo8_9_exe_DLLS:%=-l%) $(demo8_9_exe_LIBRARIES:%=-l%)


$(t3dconsole_exe_MODULE): $(t3dconsole_exe_OBJS)
	$(CXX) $(t3dconsole_exe_LDFLAGS) -o $@ $(t3dconsole_exe_OBJS) $(t3dconsole_exe_LIBRARY_PATH) $(DEFLIB) $(t3dconsole_exe_DLLS:%=-l%) $(t3dconsole_exe_LIBRARIES:%=-l%)




